port: 4000
analytics: null
host: 0.0.0.0
compress_html:
  clippings: all
  ignore:
    envs: development
chrome_mobile_color: 4B6A78
safe: false
sass:
  sass_dir: _sass
  style: compressed
url: https://shakeabi.github.io
compress-site: yes
encoding: utf-8
title: Abishake's Resume
baseurl: /resume
description: Abishake's Resume :)
theme_skin: green
pdfconvertkey: 60f51d12-e2e9-4eee-8413-afef533a9469
